### ISSUE TITLE
make:crud - Allow developer to use its own global bootstrap theme

### ISSUE THREAD

**Issue by tbordinat** [pretorien/adminlte-maker#4]
Allow developer to configure adminlte_maker this way :

```yaml
admin_lte_maker:
    base_layout:          'base.html.twig'
    datatable:
        cdn_css:  ~
        cdn_js:   ~
```

~ or something else, indicating that "I don't want the twig files to contain those lines :" 

```twig

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="*"/>
{% endblock %}

# And this one
    <script type="text/javascript" src="*"></script>
```
